swagger: "2.0"
info:
  title: Simple JWT API
  description: Simple JWT API documentation.
  version: 1.0.0
host: 127.0.0.1:9000
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  api_key:
    type: apiKey
    name: Authorization
    in: header
tags:
  - name: Auth
    description: This route is auth protected.
paths:
  /v1/auth:
    get:
      summary: Get user object.
      description: Get a the logged in user object.
      security:
        - api_key: []
      tags:
        - Auth
      responses:
        200:
          description: OK
  /v1/auth/login:
    post:
      summary: User login.
      description: Generate an auth token after validating user credentials.
      responses:
        200:
          description: OK
  /v1/auth/signup:
    post:
      summary: User signup.
      description: Create user object on the api.
      responses:
        200:
          description: OK
  /v1/auth/logout:
    post:
      summary: User Logout.
      description: Deactivate a user's auth token.
      security:
        - api_key: []
      tags:
        - Auth
      responses:
        200:
          description: OK
  /v1/auth/refresh:
    post:
      summary: Refresh auth token.
      description: Generate a new auth token for a user and deactivate the previous token.
      security:
        - api_key: []
      tags:
        - Auth
      responses:
        200:
          description: OK